################################ -*- Ruby -*- #################################
# Common tasks
#

require("../../../admin/rakehelper.rb")

package = "dynamic-spaces"

desc "Generate README.md"
task "readme" do
  sh "emacs", "-batch", "-l", "../../el2markdown/el2markdown.el",
     "../dynamic-spaces.el", \
  "-f", "el2markdown-write-readme"
end

desc "Generating html"
task "html" => ["readme"] do
  sh "markdown ../README.md > ../README.html"
end
